version: 2
jobs: 
  build: 
    docker:
      - image: circleci/node:8.9.4
    steps: 
      - checkout
      - run: 
          command: |
              wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
              ./sfdx-cli-*/install
          name: "Install SFDX"
      - run: 
          command: "echo $DEV_HUB_AUTH_URL > /tmp/sfdx.url"
          name: "Create temp sfdxurl file"
      - run: 
          command: "sfdx force:auth:sfdxurl:store -f /tmp/sfdx.url -a circle_build_$CIRCLE_BUILD_NUM --setdefaultdevhubusername"
          name: "Authorize DeveloperHub Org"
      - run: 
          command: "sfdx force:org:create -f config/project-scratch-def.json --setdefaultusername -a circle_build_$CIRCLE_BUILD_NUM\n"
          name: "Create Scratch Org"
      - run: 
          command: "sfdx force:source:push;"
          name: "Push source code"
      - run: 
          command: "sfdx force:user:permset:assign -n Random_Dog"
          name: "Assign permission set"
      - run:
          command: |
            sfdx force:apex:test:run --wait 6 --resultformat tap --codecoverage -d test_results
            dx-utils/parse_test_results.js >> test_results/test-result.txt
          name: "Run Unit Tests in Scratch Org and parse results"
      - store_artifacts: 
          destination: test-result.txt
          path: test_results/test-result.txt
      - run: 
          command: "sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p\n"
          name: "Delete Scratch Org"
      - store_test_results:
          path: test_results
version: 2