public class AssignPermissionSet {
//@InvocableMethod(label='Compute datetime' description='Computes dates from text input')

//public static list<String> PermissionSetAssign (list<PermissionSetAssignment> PermissionSet2) {
        
//        list<PermissionSetAssignment> newpermset = new List<PermissionSetAssignment>();
//    For (PermissionSetAssignment psa : PermissionSet2){
//        newpermset.add(new PermissionSetAssignment(AssigneeId = psa.AssigneeId,
//                                                   PermissionSetId = psa.PermissionSetId)
//        );
//            }
          //  PermissionSetAssignment p = new PermissionSetAssignment(AssigneeId = '005j000000C7sAJ', PermissionSetId = '0PSj0000000NKBg');
    //newpermset.add(p);
//        System.debug('UserId ' + newpermset.size());
//            insert newpermset;
        
        /* Class must return no more than 1 item. String used as return value to Flow until Collections can be returned.
         * Essentially a dummy item */
        
        
        /* Query to pull all Schedule Connections passed to class.
        *  Can likely remove when can pass in full Sobject from Flow */
// return null;       
//}
}